language: node_js
node_js:
- 0.12
env:
  matrix:
  - MY_VAR=EverythignIsAwesome
  - NODE_ENV=TEST
deploy:
  - provider: heroku
  - secure: 1OUPdn4v/R1XgzZRi6Q6Elb822D1O4aKGXWu804RDWihDjAPvMJFlsqc0s3xCZB1iUC4ff3pWvWTLHn1e5k9ypoG8GebiBOWUELs51BfTK0G5+1vg1WGI+1bEvJICSZ4QVQVU5XzaTS29TtdgUuEcbL/Hh96mIoJit7JOii5TPz+RSMopzQEHaw1syMtTkwSHlq5PNkaprzDJ8KgCPTqCbrRJOMs7gm36pG9b/SMAXV9KNZmAC/GAOy5ypIkk+U/R7qfJd9O9AvcXDFyh2qyi2hDp66EUSIvVMgo54PEF7rqWcljJaiVL/6/HGsN8KAU7ivf10GkguqBuXfGhm/gC+0FUYAhkAhvVnWGte73JtUQknHd1HEtk0T7EVPW3mPv/55N42kguFrjScUwuYu/ZNm/1TjwrzivXaSGrQpOFEzoNDkmnGasc85VhqL3NeRQdi5zWL8VjPOC2E/Tz+Iz2U/QJUUytUdEbvxhm0ZWSf7HRkwgWH/Q4+NJ+xcn0d2JirDttj4FprbH/7FsMiFyorefCr0oHijKKsaRQBUVTB0xgqXKK76nPo5pvCRWIWkbRDKdlUnmuWp8+7Msknv6lZjKoGtCXL4Em+y8q1h0XSnwxoZKg4F+jkkhFjPnxaI03GDiT5pwHHMz9agjzLU6I1eaf+uqzOuw0qDk3falGmg=
